defailt: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: qwerty

development:
  <<: *default
  database: todolist_development

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  database: todolist_production
